title: Slice_VCDC
description: >
  A FEASTorg project page for Slice VCDC.
baseurl: "/Slice_VCDC"
url: "https://feastorg.github.io"

remote_theme: pmarsceill/just-the-docs
color_scheme: feast

aux_links:
  "← Return to FEASTorg":
    - "//feastorg.github.io"

aux_links_new_tab: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM

permalink: /:path/

exclude:
  - TODO.md
  - kibot/index_template.md
  - kibot/config.kibot.site.yml
  - README.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

just_the_docs:
  logo:
    alt: "Slice VCDC"
  show_nav_level: 2
  collections:
    enable: false
